# Generated by Django 5.0.1 on 2024-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homephotoroom',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
