# Generated by Django 5.0.1 on 2024-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_homephotoroom_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutgallery',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='aboutstaff',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='aboutvideos',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='aboutvideos',
            name='video',
            field=models.FileField(upload_to='videos/display/'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='homephoto1',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='homephotoroom',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='homephotouniform',
            name='photo',
            field=models.ImageField(upload_to='images/display/'),
        ),
    ]
