# Generated by Django 5.0.1 on 2024-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_lessontable_tabletime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='images/display/')),
            ],
        ),
    ]
