# Generated by Django 5.0.1 on 2024-03-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logo',
            new_name='LogoFoto',
        ),
    ]
