# Generated by Django 5.0.1 on 2024-03-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_logo_logofoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='+998', max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_address', models.URLField(blank=True, null=True)),
                ('youtube_address', models.URLField(blank=True, null=True)),
                ('telegram_channel_address', models.URLField(blank=True, null=True)),
                ('instagram_address', models.URLField(blank=True, null=True)),
                ('telegram_bot_address', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
