# Generated by Django 5.0.1 on 2024-09-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvideos',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='aboutvideos',
            name='video',
        ),
        migrations.AddField(
            model_name='aboutvideos',
            name='video_url',
            field=models.URLField(default=True),
        ),
    ]
