# Generated by Django 5.0.1 on 2024-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_contactmap_added_date_contactmap_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='address',
            field=models.CharField(default='nomalum manzil', max_length=255, verbose_name='Manzil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='email',
            field=models.EmailField(default='nomalum@email.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='fax',
            field=models.CharField(default='nomalum_fax', max_length=20, verbose_name='Faks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='phone',
            field=models.CharField(default='123456789', max_length=20, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
    ]
