from django.urls import path
from .views import (
    WorkersListView,
    WorkersUpdateView,
    WorkersDeleteView,
    WorkersDetailView,
    WorkersCreateView,
    TeachersListView,
    TeachersUpdateView,
    TeachersDeleteView,
    TeachersDetailView,
    TeachersCreateView,
    StudentsListView1,
    StudentsListView2,
    StudentsListView3,
    StudentsListView4,
    StudentsListView5,
    StudentsListView6,
    StudentsListView7,
    StudentsListView8,
    StudentsListView9,
    StudentsListView10,
    StudentsListView11,
    StudentsUpdateView,
    StudentsDeleteView,
    StudentsDetailView,
    StudentsCreateView,
    HomeView)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('workers/', WorkersListView.as_view(), name='workers_list'),
    path('<int:pk>/edit-w/', WorkersUpdateView.as_view(), name='workers_edit'),
    path('<int:pk>/delete-w/', WorkersDeleteView.as_view(), name='workers_delete'),
    path('<int:pk>/detail-w/', WorkersDetailView.as_view(), name='workers_detail'),
    path('new-w/', WorkersCreateView.as_view(), name='workers_new'),
    path('teachers/', TeachersListView.as_view(), name='teachers_list'),
    path('<int:pk>/edit-t/', TeachersUpdateView.as_view(), name='teachers_edit'),
    path('<int:pk>/delete-t/', TeachersDeleteView.as_view(), name='teachers_delete'),
    path('<int:pk>/detail-t/', TeachersDetailView.as_view(), name='teachers_detail'),
    path('new-t/', TeachersCreateView.as_view(), name='teachers_new'),
    path('students1/', StudentsListView1.as_view(), name='students_list1'),
    path('students2/', StudentsListView2.as_view(), name='students_list2'),
    path('students3/', StudentsListView3.as_view(), name='students_list3'),
    path('students4/', StudentsListView4.as_view(), name='students_list4'),
    path('students5/', StudentsListView5.as_view(), name='students_list5'),
    path('students6/', StudentsListView6.as_view(), name='students_list6'),
    path('students7/', StudentsListView7.as_view(), name='students_list7'),
    path('students8/', StudentsListView8.as_view(), name='students_list8'),
    path('students9/', StudentsListView9.as_view(), name='students_list9'),
    path('students10/', StudentsListView10.as_view(), name='students_list10'),
    path('students11/', StudentsListView11.as_view(), name='students_list11'),
    path('<int:pk>/edit-s/', StudentsUpdateView.as_view(), name='students_edit'),
    path('<int:pk>/delete-s/', StudentsDeleteView.as_view(), name='students_delete'),
    path('<int:pk>/detail-s/', StudentsDetailView.as_view(), name='students_detail'),
    path('new-s/', StudentsCreateView.as_view(), name='students_new'),

]
