# Generated by Django 5.0.1 on 2024-03-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutGallery',
        ),
        migrations.DeleteModel(
            name='AboutName',
        ),
        migrations.DeleteModel(
            name='AboutStaff',
        ),
        migrations.DeleteModel(
            name='AboutVideos',
        ),
        migrations.DeleteModel(
            name='ContactAddress',
        ),
        migrations.DeleteModel(
            name='ContactMap',
        ),
        migrations.RemoveField(
            model_name='homephoto1',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homephotoroom',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homephotouniform',
            name='author',
        ),
        migrations.DeleteModel(
            name='HomeBlog',
        ),
        migrations.DeleteModel(
            name='HomePhoto1',
        ),
        migrations.DeleteModel(
            name='HomePhotoRoom',
        ),
        migrations.DeleteModel(
            name='HomePhotoUniform',
        ),
    ]
