# Generated by Django 4.2.4 on 2023-09-05 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=30)),
                ('phone', models.CharField(default='+998', max_length=17)),
                ('photo', models.ImageField(blank=True, default='/media/about1.jpg', upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=30)),
                ('phone', models.CharField(default='+998', max_length=17)),
                ('working_time', models.IntegerField(blank=True)),
                ('level', models.CharField(blank=True, default="bo'sh", max_length=15)),
                ('photo', models.ImageField(blank=True, default='/media/about1.jpg', upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('class_id', models.IntegerField()),
                ('class_letter', models.CharField(blank=True, max_length=1)),
                ('name_father', models.CharField(max_length=55)),
                ('name_mom', models.CharField(max_length=55)),
                ('phone_father', models.CharField(default='+998', max_length=17)),
                ('phone_mom', models.CharField(default='+998', max_length=17)),
                ('photo', models.ImageField(blank=True, default='/media/about1.jpg', upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
