# Generated by Django 5.0.1 on 2024-11-29 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Sinf Nomi')),
                ('class_id', models.IntegerField()),
                ('class_letter', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('name_father', models.CharField(max_length=55, verbose_name='Otasining ismi')),
                ('name_mom', models.CharField(max_length=55, verbose_name='Onasining ismi')),
                ('phone_father', models.CharField(default='+998', max_length=17, verbose_name='Otasi telefon raqami')),
                ('phone_mom', models.CharField(default='+998', max_length=17, verbose_name='Onasi telefon raqami')),
                ('photo', models.ImageField(blank=True, default='/media/about1.jpg', upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.classname', verbose_name='Sinf')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=30)),
                ('phone', models.CharField(default='+998', max_length=17)),
                ('working_time', models.IntegerField(blank=True)),
                ('level', models.CharField(blank=True, default="bo'sh", max_length=15)),
                ('photo', models.ImageField(blank=True, default='/media/about1.jpg', upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classname',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='student.teachers', verbose_name='Sinf Rahbari'),
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=30)),
                ('phone', models.CharField(default='+998', max_length=17)),
                ('photo', models.ImageField(blank=True, default='/media/about1.jpg', upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
